# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Rythm_config = debug

else ifeq ($(config),release)
  Rythm_config = release

else ifeq ($(config),dist)
  Rythm_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Rythm

.PHONY: all clean help $(PROJECTS) Core

all: $(PROJECTS)

Core: Rythm

Rythm:
ifneq (,$(Rythm_config))
	@echo "==== Building Rythm ($(Rythm_config)) ===="
	@${MAKE} --no-print-directory -C rythm/src -f Makefile config=$(Rythm_config)
endif

clean:
	@${MAKE} --no-print-directory -C rythm/src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Rythm"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"